import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
	static String[] allAnswers = null;
	static int[] allScores = new int[3];
	public static final String screenshotDirectory = "D:\\\\Users\\\\James\\\\Desktop\\\\Screen Shot.png";
	
	public static void main(String[] args) throws IOException {
		ImageProcessor processor = new ImageProcessor(screenshotDirectory);
		googleSearcher.loadFullSearchableText(processor.getQuestionText());
		allAnswers = processor.getAnswerList();
		
		System.out.println(processor.getQuestionText());
		
		for (String o : allAnswers) {
			System.out.println(o);

		}
	
		
		for (int i = 0; i < 3; i++) {
			allScores[i] += Algorithms.occuranceAlgorithmScore(
					googleSearcher.getFullSearchableText(), allAnswers[i]);
			System.out.println(googleSearcher.getFullSearchableText());
		}
		System.out.println(allScores[0]);
		System.out.println(allScores[1]);
		System.out.println(allScores[2]);
	}
}
