import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
	static String[] allAnswers = null;
	static int[] allScores = new int[3];
	static String questionText;
	static String fullSearchableText;
	public static final String screenshotDirectory = "D:\\Users\\James\\Desktop\\";
	public static final String screenshotIdentifier = "testscreenshot.png";
	
	
	
	
	
	public static void main(String[] args) throws IOException {
		// new ConsoleOutput().setVisible(true);
		ImageProcessor processor = new ImageProcessor(screenshotDirectory + screenshotIdentifier);
		questionText = processor.getQuestionText();		
		allAnswers = processor.getAnswerList();
		System.out.println(processor.humanQuestionText);
		fullSearchableText = googleSearcher.loadFullSearchableText(questionText);
		
		
		for (String o : processor.humanAnswerText) {
			System.out.println("***" + o);

		}
	
		// System.out.println(fullSearchableText);
		for (int i = 0; i < 3; i++) {
			allScores[i] += Algorithms.occuranceAlgorithmScore(
					fullSearchableText, allAnswers[i]);
			System.out.println(processor.humanAnswerText[i] + ": " + allScores[i]);
		}
		
		
	}
}
