/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consoleOutput;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.io.PrintStream;

import javax.swing.JPanel;
import javax.swing.JTextArea;

import main.Config;

/**
 *
 * @author Roshan
 */
public class CashShowNew extends javax.swing.JFrame {
	public boolean isFirstTime = true;
	PrintStream printStream;
    /**
     * Creates new form CashShowNew
     */
	
	public PrintStream standardOut;
    public CashShowNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        questionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bestAnswerLabel = new javax.swing.JLabel();
        bestAnswerField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        statusField = new javax.swing.JTextField();
        settingsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        questionField = new javax.swing.JTextArea();
        
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        
//        darkTheme();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        textArea = new JTextArea(200, 10);
		textArea.setEditable(false);
		printStream = new PrintStream(new CustomOutputStream(textArea));

        questionLabel.setFont(new java.awt.Font("Helvetica", 0, 50)); // NOI18N
        questionLabel.setText("Question: ");

        questionField.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        
//        questionField.setText("");
//        questionField.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Answer Choices", "Score", "Confidence"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        questionLabel.setBackground(null);
        
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(300);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(300);
        }

        bestAnswerLabel.setText("Best Answer:");
        bestAnswerLabel.setFont(new java.awt.Font("Helvetica", 0, 20));

        bestAnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestAnswerFieldActionPerformed(evt);
            }
        });

       questionField.setColumns(20);
       questionField.setRows(5);
       questionField.setLineWrap(true);
       jScrollPane3.setViewportView(questionField);
        
        statusLabel.setText("Status");

        settingsLabel.setText("Settings");
        settingsLabel.setFont(new java.awt.Font("Helvetica", 0, 20));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        yes.setText("Live Show");
        yes.setFont(new java.awt.Font("Helvetica", 0, 20));
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setText("Pre-recorded Show");
        no.setFont(new java.awt.Font("Helvetica", 0, 20));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        
        questionField.setFont(new java.awt.Font("Helvetica", 0, 15));
        
        buttonGroup1.add(yes);
        buttonGroup1.add(no);
        
        no.setSelected(true);
        
        setSize(750, 980);//this.getHeight());
        
        darkTheme();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(no)
                    .addComponent(questionLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bestAnswerLabel)
                        .addGap(25, 25, 25)
                        .addComponent(bestAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(settingsLabel)
                    .addComponent(yes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestAnswerLabel)
                    .addComponent(bestAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(settingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(no)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    public void bestAnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    public void yesActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    	Config.isLiveShow = true;
    	Config.printStream.println("Is Live Show: " + Config.isLiveShow);
    }                                   

    public void noActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    	Config.isLiveShow = false;
    	Config.printStream.println("Is Live Show: " + Config.isLiveShow);
    }    
    
    public void println(String str) {
    	if(isFirstTime) {
			printStream.append(str);
		} else {
			printStream.append("\n" + str);
		}
		isFirstTime = false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashShowNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashShowNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashShowNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashShowNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashShowNew().setVisible(true);
            }
        });
    }
    
    public double getConsoleHeight() {
		return  (Math.round(this.getInsets().top / 10.0) * 10);
	}
    
    public void darkTheme() {
    	java.awt.Color bg = new java.awt.Color(255,255,255);
    	java.awt.Color fg = new java.awt.Color(255,165,0);
    	java.awt.Color hi = new java.awt.Color(232,150,0);
    	java.awt.Color so = new java.awt.Color(201,130,0);
    	java.awt.Color si = new java.awt.Color(183,119,0);    	
    	javax.swing.border.BevelBorder b = new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED,
    			fg, hi, so, si);
    	
    	setContentPane(new GradientPanel());
    	questionLabel.setForeground(fg);
    	bestAnswerLabel.setForeground(fg);
    	settingsLabel.setForeground(fg);
    	statusLabel.setForeground(fg);
    	
    	yes.setForeground(fg);
    	no.setForeground(fg);
    	textArea.setBackground(bg);
    	
//    	no.setBackground(new java.awt.Color(172,22, 103));
//    	yes.setBackground(new java.awt.Color(172,22, 103));
    	
    	bestAnswerField.setBorder(b);
    	questionField.setBorder(b);
    	textArea.setBorder(b);
    	jTable1.setShowVerticalLines(true);
    	
    	questionField.setEditable(false);
    	questionField.setEnabled(false);
    	
    }

    // Variables declaration - do not modify                     
    public javax.swing.JTextField bestAnswerField;
    public javax.swing.JLabel bestAnswerLabel;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextArea textArea;
    public javax.swing.JTextArea questionField;
    public javax.swing.JRadioButton no;
    public javax.swing.JLabel questionLabel;
    public javax.swing.JLabel settingsLabel;
    public javax.swing.JTextField statusField;
    public javax.swing.JLabel statusLabel;
    public javax.swing.JRadioButton yes;
    // End of variables declaration                   
}

class GradientPanel extends JPanel {

	@Override
	protected void paintComponent(Graphics g) {
		super.paintComponent(g);
		Graphics2D g2d = (Graphics2D) g;
		g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
		int w = getWidth();
		int h = getHeight();
		Color color2 = new Color(255,0,91);
		Color color1 = new Color(108, 41, 114);
		GradientPaint gp = new GradientPaint(0, 0, color1, 0, h, color2);
		g2d.setPaint(gp);
		g2d.fillRect(0, 0, w, h);
	}
}